version: "3"

services:

  cadvisor:
    image: google/cadvisor
    restart: always
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
    networks:
      - backend

  node-exporter:
    image: prom/node-exporter
    restart: always
    ports:
      - 9100:9100
    depends_on:
      - cadvisor
    networks:
      - backend

  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor
    networks:
      - backend

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks:
      - backend
      - frontend

networks:
  backend:
    internal: true
  frontend:
    internal: false
